name: Generate Pac-Man Contribution Graph
on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Step 1: Generate the Pac-Man contribution graph SVGs
      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Comma-separated list of game names to generate. Default: pacman
          games: "pacman"

      # Step 2: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
